### PR TITLE
migration to grails 4

### PR DESCRIPTION
**Pull request by zhuravskiy**

### CODE REVIEW

**Comment by jamesdh** [comment]
@zhuravskiy not sure if you noticed but there are some tests failing related to `Date.plus()` and `Date.minus()` operators. I took a quick glance and it's not obvious to my why it's failing at the moment, but just wanted to make you aware.

**Comment by zhuravskiy** [comment]
@jamesdh oh thank you, fixed this problem, please review again. :pray:

**Comment by jamesdh** [comment]
Looks good to me! @longwa any chance you could take a look?

**Comment by longwa** [comment]
Thanks! I’ll take a look tomorrow.

**Pull request merged**
