### PR TITLE
Fixes #64 - No such property: application for class: grails.buildtestdata.BuildTestDataGrailsPlugin

### LINKED ISSUE #64: No such property: application for class: grails.buildtestdata.BuildTestDataGrailsPlugin
Using Grails `3.2.0.RC1` and `3.0.0` version of the plugin I get the following error during integration tests:

```groovy
Caused by: groovy.lang.MissingPropertyException: No such property: application for class: grails.buildtestdata.BuildTestDataGrailsPlugin
    at grails.buildtestdata.BuildTestDataGrailsPlugin$_closure1.doCall(BuildTestDataGrailsPlugin.groovy:32)
```

Full Stacktrace:

https://gist.github.com/rpalcolea/cf7be13d2cbbd803c05c4976540441f4

### PR DESCRIPTION
**Pull request by rpalcolea**
More details here: https://github.com/longwa/build-test-data/issues/64

I didn't touch the sample app, I don't know if this is the proper way to contribute.

### CODE REVIEW

**Comment by longwa** [comment]
@rpalcolea Thanks for the pull request. Did you happen to check if this is still compatible with Grails 3.0 and 3.1 versions? If so, I'll merge and push out a new release assuming all the tests pass.

**Comment by rpalcolea** [comment]
Hi @longwa 

Not yet, I can test the book store app against my changes. Is that a good way to make sure it works?

**Comment by longwa** [comment]
In the top level, you should be able to run `./gradlew test` to run the entire suite of tests in each of the test applications.

**Comment by rpalcolea** [comment]
Awesome I'll do that and let you know the results. Probably tonight.

**Comment by rpalcolea** [comment]
Hi @longwa 

I ran the tests and all looks ok. I guess I don't need to change anything since I looked at the `build.gradle` files of the test apps and it has `compile project(":build-test-data")` so it should be using my change. Am I correct?

```
➜  build-test-data git:(issue-64) ✗ ./gradlew test                                                                                    
:build-test-data:compileAstJava UP-TO-DATE
:build-test-data:compileAstGroovy UP-TO-DATE
:build-test-data:processAstResources UP-TO-DATE
:build-test-data:astClasses UP-TO-DATE
:build-test-data:compileJava UP-TO-DATE
:build-test-data:configScript UP-TO-DATE
:build-test-data:compileGroovy UP-TO-DATE
:build-test-data:copyAstClasses UP-TO-DATE
:build-test-data:copyAssets UP-TO-DATE
:build-test-data:copyCommands UP-TO-DATE
:build-test-data:copyTemplates UP-TO-DATE
:build-test-data:processResources UP-TO-DATE
:build-test-data:classes UP-TO-DATE
:build-test-data:compileTestJava UP-TO-DATE
:build-test-data:compileTestGroovy UP-TO-DATE
:build-test-data:compileWebappGroovyPages UP-TO-DATE
:build-test-data:compileGroovyPages UP-TO-DATE
:build-test-data:jar UP-TO-DATE
:alternativeConfig:compileJava UP-TO-DATE
:alternativeConfig:compileGroovy UP-TO-DATE
:alternativeConfig:processResources UP-TO-DATE
:alternativeConfig:classes UP-TO-DATE
:alternativeConfig:compileTestJava UP-TO-DATE
:alternativeConfig:compileTestGroovy UP-TO-DATE
:alternativeConfig:processTestResources UP-TO-DATE
:alternativeConfig:testClasses UP-TO-DATE
:alternativeConfig:test UP-TO-DATE
:baseTests:compileJava UP-TO-DATE
:baseTests:compileGroovy UP-TO-DATE
:baseTests:processResources UP-TO-DATE
:baseTests:classes UP-TO-DATE
:baseTests:compileTestJava UP-TO-DATE
:baseTests:compileTestGroovy UP-TO-DATE
:baseTests:processTestResources UP-TO-DATE
:baseTests:testClasses UP-TO-DATE
:baseTests:test UP-TO-DATE
:baseTests:compileIntegrationTestJava UP-TO-DATE
:baseTests:compileIntegrationTestGroovy UP-TO-DATE
:baseTests:processIntegrationTestResources UP-TO-DATE
:baseTests:integrationTestClasses UP-TO-DATE
:baseTests:integrationTest
:baseTests:mergeTestReports
:baseTests:test
:bookStore:compileJava UP-TO-DATE
:bookStore:compileGroovy
:bookStore:processResources
:bookStore:classes
:bookStore:compileTestJava UP-TO-DATE
:bookStore:compileTestGroovy
Download https://repo.grails.org/grails/core/org/grails/grails-datastore-test-support/4.0.7.RELEASE/grails-datastore-test-support-4.0.7.RELEASE.pom
Download https://repo.grails.org/grails/core/org/grails/grails-datastore-test-support/4.0.7.RELEASE/grails-datastore-test-support-4.0.7.RELEASE.jar
:bookStore:processTestResources
:bookStore:testClasses
:bookStore:test
:bookStore:compileIntegrationTestJava UP-TO-DATE
:bookStore:compileIntegrationTestGroovy
:bookStore:processIntegrationTestResources UP-TO-DATE
:bookStore:integrationTestClasses
:bookStore:integrationTest
:bookStore:mergeTestReports
:bookStore:test
:build-test-data:processTestResources UP-TO-DATE
:build-test-data:testClasses UP-TO-DATE
:build-test-data:test

BUILD SUCCESSFUL

Total time: 1 mins 21.179 secs
➜  build-test-data git:(issue-64) ✗ 
```

**Comment by rpalcolea** [comment]
Hi @longwa 

Any update on this? :)

**Comment by rpalcolea** [comment]
:)

**Pull request merged**
